In [3]:
# Pandas 활용 ohe

import pandas as pd

df = pd.DataFrame({'country':['russia', 'germany', 'australia', 'korea', 'germany']})
a = pd.get_dummies(df, prefix = ['country'])
a

country_australia  country_germany  country_korea  country_russia
0                  0                0              0               1
1                  0                1              0               0
2                  1                0              0               0
3                  0                0              1               0
4                  0                1              0               0

In [12]:
# pandas 활용 O H E 2

import pandas as pd
df = pd.DataFrame({
    'A': ['a', 'b', 'a'],
    'B': ['b', 'a', 'c']
})
one_hot = pd.get_dummies(df['B'])
df = df.drop('B', axis = 1)

df = df.join(one_hot)

df

A  a  b  c
0  a  0  1  0
1  b  1  0  0
2  a  0  0  1

In [15]:
# Multiple column 변환

import pandas as pd

df = pd.DataFrame({
    'A': ['a', 'b', 'b', 'c', 'a'],
    'B': ['x', 'y', 'x', 'y', 'x']
})
a = pd.get_dummies(df, prefix=['A', 'B'])
a

A_a  A_b  A_c  B_x  B_y
0    1    0    0    1    0
1    0    1    0    0    1
2    0    1    0    1    0
3    0    0    1    0    1
4    1    0    0    1    0

In [22]:
# 일부만을 자동으로 인식 encoding

import pandas as pd

df = pd.DataFrame({
    'A': ['a', 'b', 'b', 'c', 'a'],
    'B': [1, 2, 3, 4, 5]
})
x = pd.get_dummies(df, prefix = ['A'])
x

B  A_a  A_b  A_c
0  1    1    0    0
1  2    0    1    0
2  3    0    1    0
3  4    0    0    1
4  5    1    0    0

In [30]:
# One-encoding with Scikit-learn

import pandas as pd
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder

x1 = pd.DataFrame({'country':['a', 'b', 'z', 'e', 'd']})

# DataFrame 전체를 라벨인코딩(숫자로 변환) 한 후, one-hot-encoding 해야함

le = LabelEncoder()
x = x1.apply(le.fit_transform)
print(x)
print(type(x))
print()

# One hot encoding
encoder = OneHotEncoder()
x = encoder.fit_transform(x)
print(x)
print(type(x))
print()

x = x.toarray()
print(x)
print(type(x))

   country
0        0
1        1
2        4
3        3
4        2
<class 'pandas.core.frame.DataFrame'>

  (0, 0)	1.0
  (1, 1)	1.0
  (2, 4)	1.0
  (3, 3)	1.0
  (4, 2)	1.0
<class 'scipy.sparse.csr.csr_matrix'>

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]]
<class 'numpy.ndarray'>


In [33]:
# One-encoding with Scikit-learn

import pandas as pd
from sklearn.preprocessing import OneHotEncoder

x1 = pd.DataFrame({'country':['a', 'b', 'z', 'e', 'd']})



# One hot encoding
encoder = OneHotEncoder(categories = 'auto')
x = encoder.fit_transform(x1)
print(x)
print(type(x))
print()

x = x.toarray()
print(x)
print(type(x))

  (0, 0)	1.0
  (1, 1)	1.0
  (2, 4)	1.0
  (3, 3)	1.0
  (4, 2)	1.0
<class 'scipy.sparse.csr.csr_matrix'>

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0.]]
<class 'numpy.ndarray'>


In [38]:
# One-encoding with Scikit-learn

import pandas as pd
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder

x1 = pd.DataFrame({
    'A':['a', 'b', 'z', 'e', 'd'],
    'B':['x', 'y', 'x', 'y', 'x']
})

# LabelEncoding
le = LabelEncoder()
x = x1.apply(le.fit_transform)
print(x)
print(type(x), "\n")

# One Hot Encoding
encoder = OneHotEncoder(categories = "auto")
x2 = encoder.fit_transform(x)

print(x2)
print(type(x2), "\n")

x2 = x2.toarray()
print(x2)
print(type(x2), "\n")

   A  B
0  0  0
1  1  1
2  4  0
3  3  1
4  2  0
<class 'pandas.core.frame.DataFrame'> 

  (0, 0)	1.0
  (0, 5)	1.0
  (1, 1)	1.0
  (1, 6)	1.0
  (2, 4)	1.0
  (2, 5)	1.0
  (3, 3)	1.0
  (3, 6)	1.0
  (4, 2)	1.0
  (4, 5)	1.0
<class 'scipy.sparse.csr.csr_matrix'> 

[[1. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 1. 0.]
 [0. 0. 0. 1. 0. 0. 1.]
 [0. 0. 1. 0. 0. 1. 0.]]
<class 'numpy.ndarray'> 



In [45]:
# One-encoding with Scikit-learn

import pandas as pd
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

x1 = pd.DataFrame({
    'A': ['a', 'b', 'c', 'e', 'd'],
    'B': [3, 4, 5, 6, 7]
})

ct = ColumnTransformer([('one_hot_encoder', OneHotEncoder(), [0])], remainder = 'passthrough')



# LabelEncoding
le = LabelEncoder()
x1.A = le.fit_transform(x1.A)
print(x1)
print(type(x1), "\n")

# One Hot Encoding
x2 = ct.fit_transform(x1)

print(x2)
print(type(x2), "\n")


   A  B
0  0  3
1  1  4
2  2  5
3  4  6
4  3  7
<class 'pandas.core.frame.DataFrame'> 

[[1. 0. 0. 0. 0. 3.]
 [0. 1. 0. 0. 0. 4.]
 [0. 0. 1. 0. 0. 5.]
 [0. 0. 0. 0. 1. 6.]
 [0. 0. 0. 1. 0. 7.]]
<class 'numpy.ndarray'> 

